<?php

namespace AnaBundle\Repository;

/**
 * TitulacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TitulacionRepository extends \Doctrine\ORM\EntityRepository
{
}
